### ISSUE TITLE
NiViewer fails to compile on MacOSX 10.9+

### ISSUE THREAD

**Issue by jclevesque** [occipital/OpenNI2#120]
I get a bunch of deprecation errors: 

```
c++ -x c++ -c -arch i386 -arch x86_64 -msse3 -DMACOS -DGLX_GLXEXT_LEGACY -Wall -O2 -DNDEBUG -I../../../Include -I../../../ThirdParty/PSCommon/XnLib/Include -I../../../ThirdParty/GL/  -fPIC -fvisibility=hidden -Werror -o ../../../Bin/Intermediate/x64-Release/NiViewer/Draw.o Draw.cpp
Draw.cpp:385:3: error: 'glutBitmapCharacter' is deprecated: first deprecated in
      macOS 10.9 [-Werror,-Wdeprecated-declarations]
                glutBitmapCharacter(font,*str++);
                ^
/System/Library/Frameworks/GLUT.framework/Headers/glut.h:560:22: note:
      'glutBitmapCharacter' has been explicitly marked deprecated here
extern void APIENTRY glutBitmapCharacter(void *font, int character) OPEN...
                     ^
Draw.cpp:434:3: error: 'glutReshapeWindow' is deprecated: first deprecated in
      macOS 10.9 [-Werror,-Wdeprecated-declarations]
                glutReshapeWindow(g_NonFullWinSize.X, g_NonFullWinSize.Y);
                ^
/System/Library/Frameworks/GLUT.framework/Headers/glut.h:454:22: note:
      'glutReshapeWindow' has been explicitly marked deprecated here
extern void APIENTRY glutReshapeWindow(int width, int height) OPENGL_DEP...
                     ^
Draw.cpp:439:3: error: 'glutFullScreen' is deprecated: first deprecated in macOS
      10.9 [-Werror,-Wdeprecated-declarations]
                glutFullScreen();
                ^
/System/Library/Frameworks/GLUT.framework/Headers/glut.h:461:22: note:
      'glutFullScreen' has been explicitly marked deprecated here
extern void APIENTRY glutFullScreen(void) OPENGL_DEPRECATED(10_0, 10_9);
                     ^
Draw.cpp:916:15: error: 'glutBitmapLength' is deprecated: first deprecated in
      macOS 10.9 [-Werror,-Wdeprecated-declarations]
        int nWidth = glutBitmapLength(pFont, (const unsigned char*)csMessage);
                     ^
/System/Library/Frameworks/GLUT.framework/Headers/glut.h:565:21: note:
      'glutBitmapLength' has been explicitly marked deprecated here
extern int APIENTRY glutBitmapLength(void *font, const unsigned char *st...
                    ^
Draw.cpp:1215:19: error: 'glutBitmapWidth' is deprecated: first deprecated in
      macOS 10.9 [-Werror,-Wdeprecated-declarations]
        int nCharWidth = glutBitmapWidth(GLUT_BITMAP_HELVETICA_18, '0');
                         ^


    Keyboard.cpp  \
/System/Library/Frameworks/GLUT.framework/Headers/glut.h:561:21: note:
      'glutBitmapWidth' has been explicitly marked deprecated here
extern int APIENTRY glutBitmapWidth(void *font, int character) OPENGL_DE...
                    ^
Draw.cpp:1393:25: error: 'glutBitmapWidth' is deprecated: first deprecated in
      macOS 10.9 [-Werror,-Wdeprecated-declarations]
                        nLineLengthPixels += glutBitmapWidth(font, *pChar);
                                             ^
/System/Library/Frameworks/GLUT.framework/Headers/glut.h:561:21: note:
      'glutBitmapWidth' has been explicitly marked deprecated here
extern int APIENTRY glutBitmapWidth(void *font, int character) OPENGL_DE...
                    ^
Draw.cpp:1824:2: error: 'glutSwapBuffers' is deprecated: first deprecated in
      macOS 10.9 [-Werror,-Wdeprecated-declarations]
        glutSwapBuffers();
        ^
/System/Library/Frameworks/GLUT.framework/Headers/glut.h:448:22: note:
      'glutSwapBuffers' has been explicitly marked deprecated here
extern void APIENTRY glutSwapBuffers(void) OPENGL_DEPRECATED(10_0, 10_9);
                     ^
7 errors generated.
make: *** [../../../Bin/Intermediate/x64-Release/NiViewer/Draw.o] Error 1
```

This is on Mac OS 10.11. Any workarounds?

**Comment by wangyangwang** [comment]
same here

**Comment by hjmr** [comment]
Please try to install via Homebrew. NiViewere is included in brewsci/science/openni2. I am not an user of NiViewer but it looks working fine.
